import Head from "next/head";
import Image from "next/image";
import SkillCard from "../components/Skillcard";
import { skills } from "../data";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="outer-container-below-navbar">
				<h4>heading text</h4>

				<div className="skill-cards-container">
					<h3>What I do:</h3>
					<div className="skill-cards-grid">
						{skills.map((item) => (
							<div className="each-skill-card-div" key={item.title}>
								<SkillCard item={item} />
							</div>
						))}
					</div>
				</div>
			</main>
		</>
	);
}
