import ProjectCard from "../components/ProjectCard";
import { projects } from "../data";
import styles from "../styles/Projects.module.css";

import Head from "next/head";

const Projects = () => {
	return (
		<>
			<Head>
				<title>Alvin Acosta | Projects</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="initial-scale=1.0, width=device-width" />
				<link rel="icon" href="/alv.ico" />
			</Head>
			<div className={styles.projectContainer}>
				<h2>
					RECENT <span>PROJECTS</span>
				</h2>

				<div className={styles.projectGrid}>
					{projects.map((project) => (
						<div key={project.title} className={styles.projectCardDiv}>
							<ProjectCard
								image={project.image}
								title={project.title}
								srcCode={project.srcCode}
								live={project.live}
							/>
						</div>
					))}
				</div>
			</div>
		</>
	);
};

export default Projects;
